### ISSUE TITLE
Support a different service.name for the tests

### ISSUE THREAD

**Issue by v1v** [inception-health/otel-upload-test-artifact-action#8]
As far as I see this action in conjunction with https://github.com/inception-health/otel-export-trace-action are reporting to the same service name.

I think it will be handy to let the users to personalise the service name for the test results, therefore the context propagation could be the one in charge to visualise both traces together

What do you think?

**Comment by pragmaticivan** [comment]
Similar: https://github.com/inception-health/otel-export-trace-action/issues/12 The Semantic standard for OTEL was supposed to be `OTEL_SERVICE_NAME`

**Comment by nikordaris** [comment]
So the way that otel-export-trace-action is consuming and exporting this, it will overwrite the service.name set by this action. I'm open to doing a similar overwrite as is proposed in https://github.com/inception-health/otel-export-trace-action/issues/12 if this action is being used in a different way than how the companion action is using it.
